### ISSUE TITLE
service.proto not found while building with core proto

### ISSUE THREAD

**Issue by neville-nazerane** [mesg-foundation/engine#1055]
While building using the core proto in c#, I get:

>  error : Import "protobuf/definition/service.proto" was not found or had errors

>  error : "definition.Service" is not defined.

Source: https://github.com/neville-nazerane/mesg-apis

The service proto builds fine. I have tried placing the service proto in that location. I am not sure if core's proto tries to import it in some way

**Comment by antho1404** [comment]
We moved all the type's definitions in the [definition directory](https://github.com/mesg-foundation/engine/tree/v0.10.1/protobuf/definition)

Now the [CoreAPI](https://github.com/mesg-foundation/engine/blob/v0.10.1/protobuf/coreapi/api.proto) needs to import the [Service Definition](https://github.com/mesg-foundation/engine/tree/v0.10.1/protobuf/definition) ([here](https://github.com/mesg-foundation/engine/blob/7d51df3ce1ad203c87eae263d401cbf01c4d01d5/protobuf/coreapi/api.proto#L3))
There is no import needed for the ServiceAPI

I don't really know how this works in C# but you should be able to import the service definition when compiling the core api. Maybe in the worst case, you can just edit the import in the `coreapi`.

----

Also, note that the API will change in the following version. If you have a look to [the API directory](https://github.com/mesg-foundation/engine/tree/v0.10.1/protobuf/api) you will see that all the current Service and Core API will be reorganized into
- Service
- Execution
- Instance (new one coming still work in progress)

**Comment by ilgooz** [comment]
If you'd like, you can check the js version to have an idea:
* https://github.com/mesg-foundation/cli/tree/master/src/protobuf
* https://github.com/mesg-foundation/cli/blob/master/src/root-command.ts#L54-L56
