### ISSUE TITLE
Use []byte for service and instance hash (and all hash in the future)

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#1062]
In go all hashes are represented with `[]byte`. We should use []byte as type in source code. What is motivation for using string, as this is clearly the opposite direction as all golang packages (standard and non-standard)?

In the API receiving/returning string is fine, but otherwise []byte is the default type for such data.

**Comment by NicolasMahe** [comment]
I agree that internally (like in database) it should be `[]byte` and on the API it should be `string`.

I would like to keep the encoding/decoding of strign to byte inside the Engine.

**Comment by NicolasMahe** [comment]
Actually it will be nicer to use only one string representation. I really like base58 because it's the most compact with DNS valid characters.
@mesg-foundation/mesg-core-team do you agree? base58 for all hash?

**Comment by krhubert** [comment]
Also, does it make still make sense to use sid in grpc api if we will have an instance? How sid should behave then?

**Comment by antho1404** [comment]
I think sid should disappear from the apis and apis should only accept hash, it's up to the client to resolve the sid to hash.
Either check all the services and filter the one with the sid and get the list of instances for this service and pick the wanted hash or we could provide api helper if needed.
Ultimately this sid should not be part of the service but more a name service on top of the services and services are only accessible with hash

**Comment by NicolasMahe** [comment]
Closing this issue because PR https://github.com/mesg-foundation/engine/pull/1072 has been merged
