### ISSUE TITLE
sdk/instancesdk: delete should be able to optionally delete data volumes

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#1069]

**Comment by ilgooz** [comment]
not sure about having this part on instance delete(in instancesdk) or on the service delete(but in service delete grpc api - because service cannot know about instance), @mesg-foundation/mesg-core-team  feedbacks?

because it doesn't make sense for devs to delete data when stopping an instance with service:stop command. service:delete command is more related for this job

**Comment by NicolasMahe** [comment]
It's should be in instance.

Service are now ONLY holding the definition. Everything related to running a service in docker have to be in Instance.

**Comment by ilgooz** [comment]
so are we going to have the `--keepData` flag on `service:stop` cli command and once this command is executed, stop all instances belong to that service? aren't we gonna manage all instances differently for their `stop` ?

**Comment by NicolasMahe** [comment]
`service:stop` will stop only stop instances, no yes it should still manage the keepData
`service:delete` will actually remove the service, but check and return error if any instance corresponding to the service are running.
