### ISSUE TITLE
Calculate service hash

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#1081]
question: why we pass to calculate service hash dh.Sum(structhash.Sha1(srv, 1)) - dirhash already gives unique hash and service struct is just representation of definition.

The idea behind calculate service hash was to use a filesystem, so it can be calculated also in js. 

>>>
https://github.com/mesg-foundation/engine/blob/dev/sdk/service/service.go#L65

**Comment by NicolasMahe** [comment]
The goal is for the source code to be optional. A service could actually only define a workflow without any new tasks or events, this without source code.
