### ISSUE TITLE
Add back validation on service struct

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1088]
We need to add back the validation on the service, this time directly on the service.Service structure instead of the import.Service!

**Comment by NicolasMahe** [comment]
PR https://github.com/mesg-foundation/engine/pull/1099 add the validation function but now a another PR is needed to actually call the validation!

**Comment by antho1404** [comment]
There is also validation missing:
- [ ] ports
- [ ] source
- [ ] "unique" validation for arrays 
- [ ] make sure that the validation removed in the array is valid. What's the behavior when we send an array of null for example? We should require the values

**Comment by NicolasMahe** [comment]
Still missing some validation on Parameter keys: https://github.com/mesg-foundation/engine/pull/1110/files#r297480614

**Comment by NicolasMahe** [comment]
@krhubert Please check comment: https://github.com/mesg-foundation/engine/pull/1110/files#r297479535

**Comment by NicolasMahe** [comment]
@krhubert please check if can be close

**Comment by krhubert** [comment]
I've checked and the (issue)[https://github.com/mesg-foundation/engine/pull/1110/files#r297479535] is still unresolved.

**Comment by krhubert** [comment]
```
 ›   Error: duplicated mapping key at line 20, column -25:
 ›              res:
 ›              ^
```

The validation for repeted object keys is imposible because json won't allow us to send the same data multiple time (the cli parse it as error), but I've added validation anyway :)
