### ISSUE TITLE
Add deletion of instance when Engine stop

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1116]
The code to stop previously services when the Engine stop has been commented.
This need to be added back but using the instance sdk.

**Comment by antho1404** [comment]
For now, we can delete all the instances but we could also just stop them and when the engine starts it can start them back (but we can add this later)

**Comment by NicolasMahe** [comment]
@krhubert could you take a look at this one when you have time?
maybe it's already done by https://github.com/mesg-foundation/engine/pull/1087, I didn't check

**Comment by NicolasMahe** [comment]
done by #1087
