### ISSUE TITLE
All filters on gRPC APIs should be optional

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1123]
All filter on the APIs should be optional and work with default values.
If they are not set, then any value should match.
This is the list of all filters, some may already be optional (if it the case, tick the box)
- [ ] `StreamExecutionRequest.Filter.status`. default should match any status
- [ ] `StreamExecutionRequest.Filter.instanceHash`
- [x] `ListInstancesRequest.serviceHash`

**Comment by krhubert** [comment]
In proto3, all fields are "optional".

**Comment by antho1404** [comment]
but we need to treat them as optional in our apis.

For exemple, if we don't send a `status` on the `execution.stream` then we will have nothing, in that case, we should have everything.

For the second example i'm didn't try but I don't think if we have an empty `instanceHash` we will have all the execution from all instances
