### ISSUE TITLE
Execution sdk listen function implements a filter on taskKey but not the API

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1125]
https://github.com/mesg-foundation/engine/blob/e00cc7a1a3a2f20f2715d1c433537421e98ca94e/sdk/execution/execution_listener.go#L28-L30

But the API doesn't expose `taskKey` filter:
https://github.com/mesg-foundation/engine/blob/e00cc7a1a3a2f20f2715d1c433537421e98ca94e/protobuf/api/execution.proto#L32-L44

**Comment by krhubert** [comment]
Waiting for discussion in https://github.com/mesg-foundation/engine/issues/1111
