### ISSUE TITLE
Check instance is allowed to update the execution

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1139]
Instances should be authorized to update executions that are only for them:
```
request.instanceHash == execution.instanceHash
```

It could be done by a first simple system:
- add the instanceHash to every request's header that the instance is doing against the Engine.
- make the Engine check the instanceHash from the header against the instanceHash from the execution

This is not secured as instances could use the instanceHash of other instances easily.

Better system but more complicated:
- generate a couple of public and private key (maybe certificates so it's directly managed by gRPC lib)
- inject the private key in the instance's container
- make the instance to sign (and even encrypt) the request against the Engine
- the Engine verify the identity of the instance with the signature and the public key

---

A similar system should be implemented on event.create.

**Comment by krhubert** [comment]
So the first system is not worth implementing because you can just call the `Execution.Get` and insert InstanceHash, thus we need real auth system.

**Comment by NicolasMahe** [comment]
This is now done by the execution module using the runners
