### ISSUE TITLE
Remove option go_package from proto file

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1143]
The following in the proto file should be useless and can be removed as the path of the proto is the same as the generated go file:
```
option go_package = "github.com/mesg-foundation/core/protobuf/types";
```

**Comment by krhubert** [comment]
They must leave otherwise protobuf will generate:

```go
-       types "github.com/mesg-foundation/core/protobuf/types"
        grpc "google.golang.org/grpc"
        math "math"
+       types "protobuf/types"
```

for coreapi the package name will be changed, but coreapi will no longer exist anyway.
