### ISSUE TITLE
Labels on docker services

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1152]
There is a proposal to remove the name of the dependency in the service name in docker https://github.com/mesg-foundation/engine/pull/1151

This is fine but we totally lose the reference to the dependency. I suggest adding mode labels in the docker service.

Right now we have:
- mesg.engine: name of the engine
- mesg.hash: hash of the instance
- mesg.service: name of the service
- mesg.sid: sid of the service

Let's change it with the following:
- mesg.engine: name of the engine
- mesg.hash: hash of the instance
- mesg.service: hash of the service
- mesg.dependency: name of the dependency
- mesg.sid: sid of the service

**Comment by NicolasMahe** [comment]
This if required to display nicely the instances' logs in CLI.
Currently the logs will not be prefixed by the name of the dependency because the CLI doesn't know which docker service is for which dependency
