### ISSUE TITLE
Update API Core.Info

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1154]
The API Core.Info is the last old API remaining. We should move it to a new API.

@antho1404 is suggesting to use the name `Node`
Like this, we could add more functionalities: update configs, add peers, list nodes on the networks, etc..

Related proto:
https://github.com/mesg-foundation/engine/blob/49df76ec0094c0f4d89b3815e08294ab67a807e6/protobuf/coreapi/api.proto#L15-L33

The current response `InfoReply` (future `GetNodeResponse`) should be updated and simplified.
I suggest:
```proto
message GetNodeResponse {
  message SystemInstance {
    string key = 1;   // key to identify the system instance
    string hash = 2;  // hash of the instance
  }
  string version = 1; // Version of the Engine
  repeated SystemInstance systemInstances = 1; // List of the instances that the Engine is running as system instances
}
```

**Comment by NicolasMahe** [comment]
The MESG-js lib and cli should be updated when this last modif on API is done

**Comment by krhubert** [comment]
I think we should move Info api as a configuration (discussed on discord) and this is the plan, otherwise, do we want really rename it right now?

**Comment by antho1404** [comment]
no this is not a priority right now, for now this api is secondary we can leave is as undocumented and so we can break it later

**Comment by NicolasMahe** [comment]
This api will be simply removed when system services are gone. See https://github.com/mesg-foundation/engine/issues/1155#issuecomment-529284349.
We can simply remove this issue.
@antho1404 can you confirm?

**Comment by antho1404** [comment]
No, this API will still stay to provide information about the node running. We can add more information when the tendermint node is released with the list of peers connected or the last block mined etc...

I agree this might disappear in favor of multiple APIs like `peers`, `blocks`, `config`...

**Comment by NicolasMahe** [comment]
the core api has been removed. we will create a similar api when needed.
