### ISSUE TITLE
Simplification of ValidateTaskInputs

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1187]
Left only error (the same for ValidateTaskOutputs). In general ParametrWarnings should be removed. If doing so, the `RequireTask*` won't be needed anymore.

_Originally posted by @krhubert in https://github.com/mesg-foundation/engine/pull/1185_

**Comment by NicolasMahe** [comment]
`ParametrWarnings` has been removed in https://github.com/mesg-foundation/engine/pull/1309. Closing this issue.
