### ISSUE TITLE
Logs improvements

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1212]
Because of the integration of Tendermint, there is more and more logs displayed when running the engine.
We need a way to filter them by at least package name.

Logrus has a function [SetReportCaller](https://godoc.org/github.com/sirupsen/logrus#SetReportCaller) that could do the job.

Let's make sure to that the logs from cosmos are using the same system as we don't have control on those logs for now.

Hubert is suggesting to simple use `grep` to filter the logs. It could be enough..

----

Another thing that could be done is to inject as dependency Logrus to the package's struct that need it instead of using the singleton. If we do this, we need to find / define an interface so we can remove completely the import of logrus in packages (expect main that will init it).

**Comment by antho1404** [comment]
For me, the best solution would be to have a "scope" for each log that we can inject in the package. For that, we need to pass an instance of a log (with this scope/module) as a dependency (that will be good anyway) and with that, we can now grep based on this scope/module name.

```
logger = ...
moduleX = module.New(logger.WithData("module", "moduleName")

# and then when we read the logs
xxx logs | grep module=moduleName
```
