### ISSUE TITLE
Duplicate proto type event

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1236]
When running the engine on the latest version, I have the following log

```
2019/08/17 18:30:41 proto: duplicate proto type registered: types.Event
```

This should not be here and it might be an issue if there is more than one type event registered

**Comment by krhubert** [comment]
Hum that's sounds like trouble for us. The thing is they have also called package as types.

Maybe we should just add prefix `mesg.types` and keep `go_package types`. In fact, we should add mesg any of our protobuf definition to avoid such conflicts in the future.
