### ISSUE TITLE
Implement correctly cosmos account sequence

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1334]
Conversation started on https://github.com/mesg-foundation/engine/pull/1267#discussion_r321353886.

The account sequence is currently hardcoded and only work when transactions have different content.
But if 2 transactions have the same content, then they generate the same hash and thus the second is rejected.

The sequence should be always be different.
- Must the sequence number be incremented?
- Maybe use the last block height at a starting point?

**Comment by krhubert** [comment]
https://forum.cosmos.network/t/account-sequence-number/1610/2

**Comment by antho1404** [comment]
We should use the `GetSequence` from the `AccountKeeper` https://github.com/cosmos/cosmos-sdk/blob/fb3e0af0b6320838c1da8531deba6c6a542c376a/x/auth/keeper/keeper.go#L61

**Comment by NicolasMahe** [comment]
I think the Account SDK should return data from the Account Keeper. It looks like the AccountKeeper has all the data needed.
If we do this, then the functions `NewTxBuilder` and `client.BuildAndBroadcastMsg` could also accept the AccountKeeper to directly get the sequence, and account number ;)

**Comment by krhubert** [comment]
Will use GetSequence and GetAccountNumber then.

**Comment by NicolasMahe** [comment]
The `SetSequence` is already managed by cosmos when applying a transaction:
https://github.com/cosmos/cosmos-sdk/blob/02c6c9fafd58da88550ab4d7d494724a477c8a68/x/auth/ante/sigverify.go

**Comment by antho1404** [comment]
With that, we should be able to simply use `GetSequence` all the time and not have to manage the sequence at all.

**Comment by krhubert** [comment]
This is not that simple. We need to have cosmos context to get the account. 

I've used auth.NewAccountRetriver to get account number and sequence via rest api.
