### ISSUE TITLE
State modification messages should directly contain the resource to create

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1367]
The state modification messages should directly contain the resource to create.
For example in Service, the `msgCreateService` should directly contain `Service` instead of `CreateServiceRequest`.
This is only possible when #1366 is implemented.
It will force the validator of the chain to not do any processing on the data, only check and save in db.

**Comment by krhubert** [comment]
I remember I've created a version when msgCreateService holds a `Service` inside. Why we can't pass Service here? Why #1366 has to be implemented?

**Comment by NicolasMahe** [comment]
Because currently the service struct contains the hash. If we want to implement this system nicely, the data passed should not be modified. So either the hash is already calculated, otherwise the hash is not present and is calculating by the validator.

**Comment by NicolasMahe** [comment]
Because currently the service struct contains the hash. If we want to implement this system nicely, the data passed should not be modified. So either the hash is already calculated, otherwise the hash is not present and is calculating by the validator.
