### ISSUE TITLE
Service creation doesn't throw the error that the service already exists

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1382]
The Service SDK should check if a given service already exists in the database and if yes throw an error. 
Right now we have no way to know that the creation of the service failed because it exists already and we have no way to pre-calculate the hash on the client-side.

The CLI relies on this error to display error messages to the user and also handle this kind or "already exists" error

**Comment by krhubert** [comment]
I don't think it is a bug. The SDK works as we set it up.

For hash calculation, I think we should have an api to calc the service hash or just write a hash package in javascript. 

Relaying on return error string is not a good way to get hash of the service.

**Comment by NicolasMahe** [comment]
I'm ok to add a new API to check if the service already exists based on the same payload than `service.create`.

**Comment by krhubert** [comment]
I don't think exists should return a service hash. `Exists` as name provide is just to check if service exists (and not a hack for a hash calculation). For hash, it should be an API which name is "ComputeHash" or something similar or again write js package equivalent. 

Do not create/designe api for a "hack" purpose.

**Comment by NicolasMahe** [comment]
> I don't think exists should return a service hash. `Exists` as name provide is just to check if service exists (and not a hack for a hash calculation). For hash, it should be an API which name is "ComputeHash" or something similar or again write js package equivalent.
> 
> Do not create/designe api for a "hack" purpose.

I agree it’s a bit hacky to return the hash in `exists` but at the same time I would like to keep a small number of api.
What is the behavior of `get`? Does it return an error when the resource doesn’t exist or just empty? Could we use both computeHash and get?

**Comment by krhubert** [comment]
> I agree it’s a bit hacky to return the hash in exists but at the same time I would like to keep a small number of api.

In my opinion, the value of clean and readable api (without hacks) should be more appreciated then small api.

api without hack >>>>> small api.

>What is the behavior of get? 

Get returns error if service dosent' exist.
