### ISSUE TITLE
Remove service's SID

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1383]
https://github.com/mesg-foundation/engine/blob/16d8a328d291998faada8de05ad0b47d86630bbd/sdk/service/backend.go#L131-L134

This modification should be done before the hash is calculated.

Now, we cannot recalculate the hash based on the data in the database

**Comment by krhubert** [comment]
The sid should be removed as discussed previously. It should be removed before putting it on test net.

**Comment by NicolasMahe** [comment]
Sid should be simply removed.
They are currently only used to use the same volume if the service is updated:
https://github.com/mesg-foundation/engine/blob/ccf5ecc7ff60a7a02df7170b6e5c7ed07b414def/runner/builder/container.go#L267-L275

related to https://github.com/orgs/mesg-foundation/projects/25#card-34695740
