### ISSUE TITLE
Improve config validation

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1387]
From https://github.com/mesg-foundation/engine/pull/1380#discussion_r329883472

The config validation on the `Log.Format` should use `go.validator` system.
Add `oneof=text json` > https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-One_Of
With that, we can remove l149 and we could do the same for the `logLevel`.

**Comment by krhubert** [comment]
For log format yes, for log level is still better to use Parse instead of rewrite all levels from logrus :)
