### ISSUE TITLE
Improve bash dev scripts organisation

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1393]
We should improve the organisation of the bash dev scripts.
Currently we have most of them in the `./scripts` folder but also `./dev` and `./mesg-tools` in the root folder of the project.

We should improve this and find a nice way to organise them and group them.

@antho1404 is suggesting to use a make file. i like this idea. @krhubert what do you think?

**Comment by krhubert** [comment]
I really hate `Makefile`, but I don't know any better option so the obvious choice is `Makefile` grr....
