### ISSUE TITLE
Service command should have repeated string type

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#1399]
Now command type is [string](https://github.com/mesg-foundation/engine/blob/dev/protobuf/types/service.proto#L169)

It must be replaced with repeated string. String type doesn't allow to call a command with arguments that have whitespaces.

Docker command type is [slice of string](https://github.com/moby/moby/blob/master/api/types/swarm/container.go#L51) and in service_options [oversimplification](https://github.com/mesg-foundation/engine/blob/dev/container/service_options.go#L68) was made.

**Comment by antho1404** [comment]
in which case is it useful to have whitespace in arguments? From what I remember docker doesn't support space too in the commands and will ignore the rest of the command after space. If you run a command in docker with space and no array then the behavior will not be the one expected. If I remember correctly and this is right then this will not change anything and maybe we should just escape the space.

**Comment by krhubert** [comment]
> in which case is it useful to have whitespace in arguments? 

In cases where arguments require namespace :). A simple `ls "a b"` in bash receives one argument `a b` which is a directory with spaces. The same is with an executable (yes you can have exec with spaces)

> From what I remember docker doesn't support space too in the commands

Check out [swarm.ServiceSpec](https://github.com/mesg-foundation/engine/pull/1401/commits/b9dff78705c7978ce48ff5839d72cb232a529a34#diff-49c67bad953c5ce5395eec2338865746L66) in the PR. It takes command as a string slice. Docker supports is and that is exactly why we need to change it.

> we should just escape the space.

Escape the space will work only in bash and in the string it will be just a different char. Previously strings.Field was used to separate cmd so in that case it would break the command.

**Comment by antho1404** [comment]
What doesn't work with the following service:

```dockerfile
FROM ubuntu:18.04

RUN echo "1" > file1
RUN echo "2" > file2
```

```yml
name: test
sid: test
configuration:
  command: cat file1 file2
```

This works perfectly on my side so I don't see the issue here

**Comment by krhubert** [comment]
> This works perfectly on my side so I don't see the issue here.

[RUN](https://docs.docker.com/engine/reference/builder/#run) executes commands in shell this is why `RUN echo "1" > file` works for you

For the cat - you have to pass executable with spaces. So just copy cat to "cat with spaces" and try to put:
`command: cat with spaces file1 file2`

And see how will work (it won't because each argument is splited by whitespace).

Please check out the docker client API, not dockerfile or mesg config. It's completely two different things. Docker API recives slice of string (as pointed above).

**Comment by NicolasMahe** [comment]
Why not simply improving the `string` to `[]string` [function](https://github.com/mesg-foundation/engine/blob/dev/container/service_options.go#L68) by a function that split the string like shell: https://github.com/kballard/go-shellquote
Like this, no API change and the problem is fixed.

**Comment by krhubert** [comment]
> Why not simply improving the string to []string function by a function that split the string like shell: https://github.com/kballard/go-shellquote
Like this, no API change and the problem is fixed.

The problem just begins... You want to support shellquote 

- for only one of the api function or all of them? 
- which qutes does engine support?
- you need to put docs about that
- do you want to support only quotes or pipes, semicoloc etc..

So It won't be a simply solution.

So docker api is simple - recives string slice and that's it. `Dockerfile` on the other hand supports shell  or it's rather running command inside shell (which is a bit of different). But what you propose is mix two of them, nither have a simple api, nither support running in a shell.

>  The command should be used to overwrite to default command of docker, and the arguments to pass the flags.

Exacly, this is why we should have 1:1 mapping with docker api. Each of dockerfile instructions

https://docs.docker.com/engine/reference/builder/#entrypoint
https://docs.docker.com/engine/reference/builder/#cmd

Recives arrays (even withit dockerfile). What you want to do is try to find a simplification a dockerapi, which will be probably used while creating docker api at first place.

> Do you have any idea why?

Nope, but if you have that service I can check it for you.

**Comment by NicolasMahe** [comment]
> Nope, but if you have that service I can check it for you.

service-ethereum, branch `geth-light-node`
https://github.com/mesg-foundation/service-ethereum/blob/geth-light-node/mesg.yml

**Comment by krhubert** [comment]
@antho1404 @NicolasMahe  any comments on that issue?

**Comment by NicolasMahe** [comment]
I would not touch anything for now.
It's a breaking change for not a lot of value..

**Comment by NicolasMahe** [comment]
@krhubert why closing this issue but not the PR https://github.com/mesg-foundation/engine/pull/1401 ?
