### ISSUE TITLE
Issue with the rebuild of the engine in dev

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1415]
While testing https://github.com/mesg-foundation/engine/pull/1412#issuecomment-545723505

I had some issues because my docker image/binary was not re-compiled.

Even after running `make clean` I still had the previous version of my docker image and binary.

**Comment by NicolasMahe** [comment]
make clean should also delete `mesg/engine:dev` or local image

**Comment by antho1404** [comment]
Cannot reproduce anymore, this seems to be fixed
