### ISSUE TITLE
Service compilation for e2e

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1420]
We need to find a way to compile the service before running e2e in an efficient way and try to not use the CLI to avoid dependency..

  - use cli?
  - create new compile script in go?

**Comment by antho1404** [comment]
If this helps, a new library is now available `@mesg/compiler`. This library could contain a binary like `mesgc` to just compile a service or process

**Comment by NicolasMahe** [comment]
The e2e tests are not using any compilation anymore.
