### ISSUE TITLE
Create e2e process tests

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1427]
Dependant on https://github.com/mesg-foundation/engine/issues/1426

Create e2e tests for the event api with a running instance:
- [x] create https://github.com/mesg-foundation/engine/pull/1501
- [x] delete https://github.com/mesg-foundation/engine/pull/1501
- [x] get https://github.com/mesg-foundation/engine/pull/1501
- [x] list https://github.com/mesg-foundation/engine/pull/1501
- [x] process actually connect event to tasks https://github.com/mesg-foundation/engine/pull/1546
- [x] process actually connect tasks to tasks https://github.com/mesg-foundation/engine/pull/1546

**Comment by antho1404** [comment]
Adding few more things to test

- [ ] mapping based on previous data (event or result)
- [ ] filter
- [ ] multi-step

**Comment by NicolasMahe** [comment]
Example:
- https://mesg.com/mesg-orchestrator/
- https://gist.github.com/antho1404/8a02ac0dc79b3e8435fa1495dac0a51e

**Comment by NicolasMahe** [comment]
Example:
- https://mesg.com/mesg-orchestrator/
- https://gist.github.com/antho1404/8a02ac0dc79b3e8435fa1495dac0a51e

**Comment by NicolasMahe** [comment]
I will start to implement the e2e test of the orchestrator.

**Comment by NicolasMahe** [comment]
- [x] process using nested data https://github.com/mesg-foundation/engine/pull/1547
