### ISSUE TITLE
Error when starting the engine

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1457]
I got this error a couple of times. I'm still not sure how to reproduce it. It seems connected to the fact that I ran multiple engines and then when I start only one engine again I have this.

```
time="2019-11-04T03:29:08Z" level=fatal msg="failed to load Store: wanted to load target 94738 but only found up to 0" module=main
```

The solution is to delete the `.mesg` directory

**Comment by NicolasMahe** [comment]
> It seems connected to the fact that I ran multiple engines
at the same times? if yes, do you set the `MESG_PATH` individually?

**Comment by antho1404** [comment]
yes multiple engines at the same time and yes with different path (using the cli) but I don't have any way to reproduce yet.

**Comment by antho1404** [comment]
I was able to reproduce it by updating the docker service.

```
mesg-cli daemon:start --path ~/.mesg/mesg-testnet-01 # my testnet sync, I'm not sure this is relevant 
docker service update --publish-add 26657:26657 engine
mesg-cli daemon:logs 
# time="2020-02-13T04:07:53Z" level=fatal msg="failed to load Store: wanted to load target 337590 but only found up to 0" module=main
```

**Comment by NicolasMahe** [comment]
i think this is the same problem as
