### ISSUE TITLE
Use a single cosmos account across the Engine

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1458]
Simplify the account management to use only one account across the Engine.
This account should be define in the Config.
The credentials system and account sdk should stay be not be used.

**Comment by krhubert** [comment]
What is the reason for that?

**Comment by NicolasMahe** [comment]
As discussed during the meeting, the engine needs the sign transaction by itself without asking for the user to do it. So, the ultimate solution is to create multiple account and let the user authorize an account for the engine to use. The quick solution (this issue) is to hide the multiple account management from the engine, generate automatically one account on engine start (if it doesn't already exist) and use it to sign any transactions.

**Comment by krhubert** [comment]
But we have already a "dev" account, can't engine use that account to sign and left other accounts untouched? 

If this is the only solution then merge the PR, but I don't get it why to create user needs a change.

**Comment by NicolasMahe** [comment]
> But we have already a "dev" account, can't engine use that account to sign and left other accounts untouched?

that's basically what what this issue is about. but instead of naming it `dev`, it's the `engine` account also useful for non-dev utilization.
