### ISSUE TITLE
Use cosmos errors for the backend

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1471]
In many places in the sdk backend we use normal errors instead of cosmos errors.
We eventually transform these errors into `ErrInternal` [here](https://github.com/mesg-foundation/engine/blob/caeaa28ee71365af56a0b0d40804f0ed58c6b5d8/sdk/service/backend.go#L56)

So we should consider using directly cosmos errors for the backend as they provide more context `ErrInsufficientFunds`, `ErrInvalidAddress`, `ErrUnauthorized`...

**Comment by NicolasMahe** [comment]
Even further, the handler functions of sdks should accept classic error and cosmos error type and transform the classic error to cosmos error automatically (like the querier functions)

**Comment by krhubert** [comment]
So there is a draft. We need to decide what errors we want to have and just start using them. I put few example errors. We can create more over the time. Waiting for your commnet.

**Comment by NicolasMahe** [comment]
After meeting with @krhubert, we decided to implement one new `CodespaceType` `mesg` that will contains error related to the project added value (running services, executions, processes) and not to error related to the blockchain (those one should use the `sdk` codespace [defined by cosmos](https://github.com/cosmos/cosmos-sdk/blob/d81d46192a0c26a4ed8bec911813b3239c14a55e/types/errors.go#L56-L57).

We will also implement new `CodeType` for any error that is not [already defined by cosmos](https://github.com/cosmos/cosmos-sdk/blob/d81d46192a0c26a4ed8bec911813b3239c14a55e/types/errors.go#L31-L51).

**Comment by krhubert** [comment]
As discussed, we're gonna create those errors as needed during development, so closing this issue for now.
