### ISSUE TITLE
Registration of runners

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1472]
Right now running a runner is the following process:

- Calculate the future instance hash
- Build the image
- Start the container
- Send a transaction with the information that was needed to calculate the instance hash

This is a bit weird to have to calculate the instance hash and to then send a transaction with all the info to calculate this same hash.

We could have a runner in 2 steps.
- First, we register as a runner
  - Create a transaction with the info to calculate the instance hash
- We start the instance
  - Wait for the confirmation of the transaction
  - Build the image
  - Start the container
  - We could send a transaction to set that the runner is "ready"

This could be interesting for different reasons. First, we don't need to precalculate the hash and just rely on the data that were validated by the validator. Second, thanks to that we could have some checks that the service is actually running.
Example:
- First transaction with information of the hash
- Validator create the runner with a challenge
- The runner waits for the transaction and when the container is running we could inject this challenge in docker secret or something like that
- The service solves this challenge
- The engine sends a transaction to mark as "ready" with the proof of the challenge

**Comment by NicolasMahe** [comment]
> This is a bit weird to have to calculate the instance hash and to then send a transaction with all the info to calculate this same hash.

The instance hash calculation can be replaced by another deterministic hash or even an UIID (if we save it).

> This could be interesting for different reasons. First, we don't need to precalculate the hash and just rely on the data that were validated by the validator. Second, thanks to that we could have some checks that the service is actually running.

I like this part ;)

**Comment by NicolasMahe** [comment]
related to https://github.com/orgs/mesg-foundation/projects/25#card-34695740

**Comment by NicolasMahe** [comment]
This is now done:
The CLI generated a signature, inject it in the runner, the runner uses this signature to register itself on the orchestrator.
