### ISSUE TITLE
Make amino support map for binary encoding

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1492]
Currently Amino doesn't work when encoding map in binary:
- https://github.com/tendermint/go-amino/issues/4
- https://github.com/tendermint/go-amino/issues/154#issuecomment-392421945

Amino can also encode map in json, not binary.
So the `Struct` is not working with amino:
https://github.com/mesg-foundation/engine/blob/940abdaa67779f39482e03b0bb6afbac0a05b745/protobuf/types/struct.pb.go#L60-L66

Here is the unit test that currently expect a panic:
https://github.com/tendermint/go-amino/blob/fbf776258498dbb3aa6637ca82c7fe5c7255fd2f/binary_test.go#L269-L290

---

One solution: use json encoding instead of binary.

I tried to update the engine codebase to use json encoding but there is one issue with a cosmos module that force to encode in binary (default txEncoded and txDecode of cosmos):
https://github.com/cosmos/cosmos-sdk/blob/95ddc242ad024ca78a359a13122dade6f14fd676/x/genutil/gentx.go#L99
The function `DeliverGenTxs` should also receive as parameter a `encodeTx` function that is set by the app.

One way to do is to fork cosmos-sdk to add a new parameter to this function and update the rest of the codebase.

---

Other solution, make amino compatible with binary.

this [comment](https://github.com/tendermint/go-amino/issues/154#issuecomment-392421945) is suggesting a few solution:
> Solution 1: Make interface{} encoding in Amino:JSON to deal with primitive types by default, so you don't have to register ints (and they would appear as unwrapped e.g. 3), whereas registered concrete types can have type wrappers. Maybe we want the ability to register concrete types in the context of a map or interface{} field.
> 
> Solution 2: #123 .
> 
> Solution 3: Make a type type PrimitiveMap map[string]interface{} with MarshalAmino()/UnmarshalAmino() implemented, where the only allowed values are primitive types, so there's no need for concrete type registration under the interface.

I think we should explore the 3 solutions, if none work, fork amino and implement the map in the following files:
- https://github.com/tendermint/go-amino/blob/master/binary-encode.go
- https://github.com/tendermint/go-amino/blob/master/binary-decode.go

**Comment by NicolasMahe** [comment]
You can also check branch `exp/codec-json` for the version with JSON encoding everywhere (except in https://github.com/cosmos/cosmos-sdk/blob/95ddc242ad024ca78a359a13122dade6f14fd676/x/genutil/gentx.go#L99 )

**Comment by NicolasMahe** [comment]
For reference, @krhubert posted those issues:
- https://github.com/tendermint/tm-db/issues/28
- https://github.com/cosmos/cosmos-sdk/issues/5297
- https://github.com/cosmos/cosmos-sdk/issues/5298

**Comment by krhubert** [comment]
closing, as there is not optimal way to implement mas support. The decision is to drop map support.

**Comment by NicolasMahe** [comment]
Done in https://github.com/mesg-foundation/engine/pull/1502
