### ISSUE TITLE
Implement error on tm-db

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1494]
See issue https://github.com/tendermint/tm-db/issues/28

**Comment by krhubert** [comment]
On repo https://github.com/krhubert/tm-db c_level_db and go_level_db is done. But changing those two will also require changing iterator interface a bit. For them it would be tendermint it would be really a breaking change but hope they will merge that PR some day...

**Comment by NicolasMahe** [comment]
There is already a PR about this on tm-db repo https://github.com/tendermint/tm-db/pull/30

**Comment by krhubert** [comment]
Yes there is, but iterators still panics - and that was the way harder part to implement ;)

**Comment by NicolasMahe** [comment]
I'm unassigning you from the issue. It's not a priority as tm-db team is already working on it.

**Comment by marbar3778** [comment]
add errors to iterators, please comment in the PR if you have any changes you would like to see.

**Comment by NicolasMahe** [comment]
closing this issue as https://github.com/tendermint/tm-db/pull/30 has been merged! Good job @marbar3778
