### ISSUE TITLE
Make sure to sign transaction with different sequence within the "same block"

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1538]
We need to make sure that it's possible to to sign transaction with different sequence within the "same block".

The account seems to have a `SetSequence` function. Maybe we can use it to increase the sequence locally.
Have to check how it really works.

**Comment by krhubert** [comment]
Sequence is just an [int value](https://github.com/cosmos/cosmos-sdk/blob/master/x/auth/types/account.go#L31) which is [increased](https://github.com/cosmos/cosmos-sdk/blob/master/x/auth/ante/sigverify.go#L252) for every signer on each ante (tx). So, in that case, it would be increased in "the same block". 

This set sequence mechanism it's rather simple and it's not used anywhere else.

**Comment by NicolasMahe** [comment]
how does it keep the provided sequence in `SetSequence`? in memory? kvstore? does it persist? does it reset when the variable account is garbage collected?

**Comment by krhubert** [comment]
The sequence is keet in KVStore. The KVStore is supplied (as a param) to `BaseApp` and in engine case, it is [GoLevelDB](https://github.com/mesg-foundation/engine/blob/dev/core/main.go#L143)

- it's persistent 
- the account can't be garbage garbage - it has to be removed manually from the store.

**Comment by antho1404** [comment]
The `AnteHandler` of the `auth` module also increases the `Sequence` https://github.com/cosmos/cosmos-sdk/blob/02c6c9fafd58da88550ab4d7d494724a477c8a68/x/auth/ante/sigverify.go#L252.
So if we increase it manually, does it mean that we will increase it 2 times for every transaction? (this is still fine and it will work but a bit weird)

**Comment by krhubert** [comment]
> The AnteHandler of the auth module also increases the Sequence

This is the only place where the sequence is increase at the moment. We don't set seq in the engine.

**Comment by NicolasMahe** [comment]
We can keep an account in memory on the client side. Use the getSequence and setSequence to get and increase the sequence.
If the account doesn't exist, the engine should get it using the retrieve account function (it will return the account with the sequence from the blockchain).
Now, we need to sync the local in memory account sequence and the one from the blockchain. We can subscribe to the end of block event, and for each local account, set the new sequence only if it is superior to the local account's sequence.
