### ISSUE TITLE
Issue while creating multiple executions

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1539]
When we create multiple executions (pretty much at the same time) we have an error on the database that there are issues with the initialization of the database.

The issue occurs because we are reading on the keybase 
https://github.com/mesg-foundation/engine/blob/52c3b1113c488818f9f275515315ea0e3a8d9423/sdk/execution/sdk.go#L39-L42
and this keybase is recreating a new instance of the levelDB all the time.

https://github.com/cosmos/cosmos-sdk/blob/a13909a9ffaafda31c26a104a4fc97efa947f597/crypto/keys/lazy_keybase.go#L40-L48
```go
func (lkb lazyKeybase) Get(name string) (Info, error) {
	db, err := sdk.NewLevelDB(lkb.name, lkb.dir)
	if err != nil {
		return nil, err
	}
	defer db.Close()
	return newDBKeybase(db).Get(name)
}
```

You can reproduce with this https://github.com/mesg-foundation/engine/issues/1537.

Solutions to fix this:
- Use an in-memory keybase
- Fix their lazy keybase and make it concurrency safe
- Add a lock when we use the keybase (in that case we could use only the sdk and the sdk will manage the keybase)

**Comment by NicolasMahe** [comment]
> - Use an in-memory keybase

The issue will persist the account. could just save the mnemomic and generate the same account

> - Fix their lazy keybase and make it concurrency safe

best move to do but they make take long time to release even after a PR...

> Add a lock when we use the keybase (in that case we could use only the sdk and the sdk will manage the keybase)

The lock should be add in the wrapper of the keybase in the mesg package `cosmos/keybase`. but each function would need to be re-implemented.
