### ISSUE TITLE
Add node reference system to process node result as well

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1562]
We should also implement it on the node of type result as they are also linked to an execution so the outputs can be read at anytime.

**Comment by krhubert** [comment]
Hasn't it already done by @antho1404, has it?

**Comment by antho1404** [comment]
closed in favor of more check on the orchestrator https://github.com/mesg-foundation/engine/pull/1567

**Comment by antho1404** [comment]
Now we can reference a trigger with the direct child only, we should be able to reference a result trigger from any node

**Comment by NicolasMahe** [comment]
attempt done in https://github.com/mesg-foundation/engine/pull/1740
