### ISSUE TITLE
Remove service ownership

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1591]
Right now services cannot be deleted so ownership is useless. When https://github.com/mesg-foundation/engine/issues/1590 is done, the ownership store will only contain services so this store can be totally deleted.

If we need the owner we can always query on the client side the transactions that match the `createService` message.

**Comment by NicolasMahe** [comment]
Let's think again about this modification because of the soon to be implemented token economy

**Comment by NicolasMahe** [comment]
We are going to keep the ownership module and extend its functionalities with token transfers and make more resources using it.
Closing this issue.
