### ISSUE TITLE
Simplification of resources

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1593]
Some resources like services contain extra data that are not necessary to store directly on-chain.

List of things to remove:
- name
- description
- repository
- sid
- key (in some cases might be removed too)

This could be done in 2 different steps:
- [ ] Remove from the hash calculation
- [ ] Remove from the data (and find a way to store it somewhere else like IPFS for example if needed)

Example of an update to do https://github.com/mesg-foundation/engine/compare/refacto/simplification-resource

**Comment by NicolasMahe** [comment]
This makes a lot of sense when we have a website to add those data after a service is published.
Related to: https://github.com/orgs/mesg-foundation/projects/25#card-34523095
