### ISSUE TITLE
Use directly docker container instead of docker service

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1615]
Currently, the engine's docker implementation is using service rather than container.

The argument in favor of service are:
- docker is pushing on swarm-only or kubernetes and may deprecated container only api. @antho1404 i tried to find some source but couldn't find any.
- docker is managing the container and make sure to create them/replicate them. This is actually not a valid argument as container have the restart policy option and the engine will never replicate service using docker..

The argument against service:
- more complicate API. instead of creating directly the container, we are creating a service that will eventually create a container using tasks.
  those tasks are really hard to debug and get the log from. when creating directly a container, the error contained in the task are directly the error returned during the creation of the container.
  same for deletion of service. the overall logic to know if a mesg service is started, running and deleted will be MUCH simpler:
https://github.com/mesg-foundation/engine/blob/c5654e1624f83953dbaa0c5104c8dbbf347dd91d/container/container.go#L263-L269
https://github.com/mesg-foundation/engine/blob/c5654e1624f83953dbaa0c5104c8dbbf347dd91d/container/container.go#L329-L330
- less options: containers offer a lot more option than services as there is no swarm restriction.
- less complex network configuration and less limitation: because services are for multi node-swarm with automatic replication, there are a lots of network option no available or just "hardcoded" to make it run in swarm.
  For example, published port using service is available to any ip / network because of the constraints of swarm. With container, a port can be published only to localhost and not to the whole internet.
- docker compose is working well only with containers. it could be nice to use docker compose instead of our own implementation?
- more bug in docker swarm and service implementation that are not when using directly containers.
- have to manually setup docker as a swarm node.

---

this is not an urgent matter or anything, but I'm sure it will become necessary in order to increase security and bring flexibility to the engine like running the engine outside of docker and use docker only as one way to manage mesg services.

**Comment by NicolasMahe** [comment]
This issue could make those issues irrelevant:
- https://github.com/mesg-foundation/engine/issues/1159
- https://github.com/mesg-foundation/engine/issues/794
- https://github.com/mesg-foundation/engine/issues/430

**Comment by NicolasMahe** [comment]
related to https://github.com/orgs/mesg-foundation/projects/25#card-34695740

**Comment by antho1404** [comment]
this has been done in the CLI in https://github.com/mesg-foundation/js-sdk/pull/199
