### ISSUE TITLE
Reorganize project directory layout

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#1638]
As we add more stuff to engine like scripts, grafana/promethues config, dockers, cmds etc.. I suggest to change project directory layout to something similar to https://github.com/golang-standards/project-layout.

So move source code to `pkg` directory, create `configs`, `docs`, etc ...

@antho1404 @NicolasMahe any thoughts?

**Comment by antho1404** [comment]
Totally agree with that, if we can "standardize" the code organization that's great. We also have to think on how to do that correctly if we reorganize based on these multiple entrypoints that we talked about (cosmos/tendermint - orchestrator - service manager). If the proposed project layout is good it shouldn't have any impact.
