### ISSUE TITLE
Issue while connecting on an existing network

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1659]
When connecting to the testnet or a previous local net from the `dev` branch (0fc786e1128a116c7567415d4f05b917458ec863) the engins crashes with the following error:

```
FATA[0000] Error reading GenesisDoc at /root/.mesg/tendermint/config/genesis.json: evidenceParams.MaxAgeNumBlocks must be greater than 0. Got 0  module=main
```

The migration from 18.2 and 18.3 is fine, this is just on the dev

**Comment by antho1404** [comment]
This seems related to this issue https://github.com/tendermint/tendermint/issues/2565 and part of the breaking changes of the latest release https://github.com/tendermint/tendermint/blob/v0.33/CHANGELOG.md#breaking-changes

**Comment by NicolasMahe** [comment]
Tendemint v0.33 is not compatible with previous version:
https://github.com/tendermint/tendermint/blob/v0.33/UPGRADING.md#v0330
> v0.33.0
> This release is not compatible with previous blockchains due to commit becoming signatures only and fields in the header have been removed.

I tried to export txs from current testnet and broadcast them on the new version but none of them worked. Check the PR https://github.com/mesg-foundation/engine/pull/1675 to see the commands.

I'm closing this issue as we don't have any choice but to start a new version of the testnet
