### ISSUE TITLE
Refactoring list for cosmos modules

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1660]
The errors return from the modules should be wrapped otherwise they are "replaced" by a generic one "internal error" without any message.

Eg:
```diff
    hash, err := hash.Decode(path[0])
    if err != nil {
-        return nil, err
+        return nil, sdkerrors.Wrap(sdkerrors.ErrInvalidRequest, err.Error())
    }
```

**Comment by krhubert** [comment]
- [ ] Add cosmos wrap error to all module errors
- [ ] write client for module rest api
- [ ] use one function in reset/cli querier
- [ ] move common events atttributes (like `"hash"` to shared pkg)

**Comment by NicolasMahe** [comment]
i transfer the content of this issue to https://github.com/mesg-foundation/engine/issues/1639
let's keep only https://github.com/mesg-foundation/engine/issues/1639 as main issue for all those changes
