### ISSUE TITLE
Issue with the cosmos CLI

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1671]
The cosmos CLI `mesg-cosmos` has issues with amino when trigger some commands.

To reproduce:
```
git checkout dev
make build-cmd
./bin/mesg-cosmos query auth account mesgtest19k9xsdy42f4a7f7777wj4rs5eh9622h2z7mzdh
```

result:
```
ERROR: cannot parse disfix JSON wrapper: json: cannot unmarshal string into Go value of type amino.disfixWrapper
```

This issue also appears in other commands like `./bin/mesg-cosmos tx bank send`

**Comment by NicolasMahe** [comment]
i don't have issues with the cli:
```
➜  engine git:(dev) ./bin/mesg-cli query auth account mesgtest1c2r025qn4ky5n7dcmmq8tga7m7t6x77n7yv3q0
{"type":"cosmos-sdk/Account","value":{"address":"mesgtest1c2r025qn4ky5n7dcmmq8tga7m7t6x77n7yv3q0","coins":[{"denom":"atto","amount":"248999999999999999998597839"}],"public_key":"mesgtestpub1addwnpepqd0rt0ghpr58nfch89sxqk0na75gsxx99p2jeds59zuuu22ad2mevfsc80f","account_number":3,"sequence":10}}
```

➜  engine git:(dev) ./bin/mesg-cli tx send engine mesgtest1lwjv6x60z2faf0cdndl05829mwfwmpjmjhq204 10atto --chain-id mesg-dev-chain --gas-prices 1.0atto
{"chain_id":"mesg-dev-chain","account_number":"3","sequence":"1","fee":{"amount":[{"denom":"atto","amount":"200000"}],"gas":"200000"},"msgs":[{"type":"cosmos-sdk/MsgSend","value":{"from_address":"mesgtest16nec406t73x0l77kf49ecrc5aqk4fg5xn3t7v9","to_address":"mesgtest1lwjv6x60z2faf0cdndl05829mwfwmpjmjhq204","amount":[{"denom":"atto","amount":"10"}]}}],"memo":""}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"0","txhash":"10634207D6A0034D68A97C05003892705A485B4F4E328F74E6A60FC0DAA62CA5","raw_log":"[]"}

**Comment by antho1404** [comment]
Was using an old version of the CLI. Everything is fine :)
