### ISSUE TITLE
Account sequence desynchronisation

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1693]
If the transaction failed for whatever reason, the sequence count is not synchronized with the one of the blockchain.
We should delete the local account when an error occurred.
Related file:
https://github.com/mesg-foundation/engine/blob/dev/cosmos/client.go

**Comment by krhubert** [comment]
Do we want really to delete account? Can't we sync it back with blockchain on getting the Sequnce.

**Comment by NicolasMahe** [comment]
I mean the account save in memory:
https://github.com/mesg-foundation/engine/blob/4d4b8069866ce99e01334abc5913e12e78733fc0/cosmos/client.go#L177-L205
