### ISSUE TITLE
Add balance system on processes

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1698]
Processes should have their own balance where
- any user can put coins using the bank module
- only the owner of the process can withdraw (related to https://github.com/mesg-foundation/engine/pull/1688)
- execution linked to a process (`processHash` is set) should take the coins from the process and NOT from the signer of the transaction

**Comment by NicolasMahe** [comment]
Open question:
@antho1404 @krhubert  Should we force the user to transfer coins to the process on its creation? It could be done in the process module handler. Otherwise, the CLI could create a new transaction that transfers coins to the newly created process.

**Comment by antho1404** [comment]
I would recommend to keep it simple for now and we create the process and then execute a transfer to this process. 
We can, of course, send a transaction with 2 messages, one to create the process, the other one to add a balance to it. 
Ultimately we could have the optional parameter to create and deposit on the process in the same message but I think it will be overkill for now.
Also having a process with no balance is quite nice, I could deploy a process for a company but it's their responsibility to deposit on it and the process will start/work only when they deposit.
