### ISSUE TITLE
Hash as string in all proto files

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1700]
To simplify clients, we should encode the resources' hash in string in the proto files.

Like this, all the HTTP APIs of the LCD server and the soon-to-be-deprecated gRPC APIs will exchange hashes in their string version.

We currently use base58 to encode binary hashes to string.
But because of the recent implementation of the MESG Economy, we encode the resource's hash in bech32 address to be able to use the existing transfer of coins functionalities.
I'm suggesting to switch all stringify version of the hash to bench32 address so we have only one identifier for any resources!

@antho1404 @krhubert we already spoke about it on Discord, but I would like you to give your feedback or confirm this proposal.

related to https://github.com/mesg-foundation/engine/issues/1667

**Comment by antho1404** [comment]
Agree with the fact to remove the hash in the data and have the identification of a resource based on its bench32 address (that will internally hash the resource to calculate this address).

I'm not sure this is really relevant right now and high priority but definitely something to keep in mind.

**Comment by NicolasMahe** [comment]
Advantage of bench32 vs base58: https://wiki.trezor.io/Bech32

**Comment by krhubert** [comment]
There are 3 diffrent things here:

- use bech32 instead of base58 (👍 )
- use hash as resrouce address (👍 )
- keep hash as string in proto file (👎 )

For now we are still using bytes as hash types. And we were talking about using bech32 + use hash as `cosmos resource address` and I like that. 

> To simplify clients, we should encode the resources' hash in string in the proto files.

As for me, the hash should stay as bytes in the data definition, like every other hash (including cosmos address which is `[]byte`)

We'll be removing proto api soon, so I think this is not time for that now.

**Comment by NicolasMahe** [comment]
> As for me, the hash should stay as bytes in the data definition, like every other hash (including cosmos address which is `[]byte`)

Inside the engine, the hash will be `type AccAddress []byte` thanks to gogoproto custom type.
 
> We'll be removing proto api soon, so I think this is not time for that now.

But the issue is the engine is also using protobuf definition to encode in json using amino.
So either we encode different way for proto, amino, json, or we settle on only one encoding.

**Comment by NicolasMahe** [comment]
We are just going to do the same as cosmos-sdk. They encode the address in bytes on proto.
