### ISSUE TITLE
New Engine architecture

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1815]
Split the Engine into multiple smaller pieces that heavily use the cosmos CLIs:
- [x] the Engine should only manage the orchestrator and routing the event/execution to/from runners https://github.com/mesg-foundation/engine/pull/1801
- [ ] start Tendermint and the ABCI app using the Tendermint CLI
- [ ] start the cosmos LCD server using the Cosmos CLI

**Comment by williamzmorgan** [comment]
I see this is closed, but would this be useful to others if we wrote a blog post about it? If so, it seems like it would be interesting content.

**Comment by NicolasMahe** [comment]
Yes that's will be a good piece of content for mesg. Could you track this and remind me to do it please.

**Comment by williamzmorgan** [comment]
@NicolasMahe Awesome. I've created an issue for this: https://github.com/liteflow-labs/blog/issues/17 I expect that we won't need this for another couple of weeks, but I will keep you updated.
