### ISSUE TITLE
need vendoring

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#280]
could be useful:
* docker client sample:
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf

**Comment by NicolasMahe** [comment]
Fixing the version of the dependencies of this project is a good idea but which solutions to choose? There is no standard way in Go to do it.

https://blog.golang.org/versioning-proposal
https://github.com/golang/go/issues/24301

**Comment by ilgooz** [comment]
* Docker has it's own vendor definition file called [vendor.conf ](https://github.com/moby/moby/blob/master/vendor.conf). Please check [here](https://github.com/moby/moby/blob/76e43532f60355220619b5ff808c0d2cd4bd624b/hack/README.md#vendor-vendorsh). So using [vndr](https://github.com/LK4D4/vndr) is an option.
* Go offical has an experimental [dep](https://github.com/golang/dep) tool. It both has a conf yml and lock yml.

There are other popular dep tools like [govendor](https://github.com/kardianos/govendor) but I think we should stick with the official one or maybe vndr. Without the matter of which tool we use we are going to have a [standard](https://golang.org/cmd/go/#hdr-Vendor_Directories) vendor/ dir in our root.

Not directly related but also worth to see https://research.swtch.com/vgo-tour

**Comment by antho1404** [comment]
https://glide.sh/ can be a solution to explore

**Comment by krhubert** [comment]
Golang has dep as it's (semi) official tool. I've used the tool as it would be merged with go standard tools

**Comment by ilgooz** [comment]
lets consider using an automation tools to update vendor/ folder. it'd be nice to automatically update vendor/ folder depending on the changes in the vendor.conf file. this way we don't forgot about updating vendor/ folder and prevent corrupted vendor files to merge. please see:  https://dependabot.com/

**Comment by krhubert** [comment]
As @ilgooz suggested there is a  [platform](https://dependabot.com/) for automated dependency updates. It uses dep under the hood and creates PR with dependencies update.

**Comment by krhubert** [comment]
https://github.com/mesg-foundation/core/pull/342

**Comment by ilgooz** [comment]
* We can add a CI task to create automated PR's to update vendor/ for the latest version of dep conf file. This task should run in daily basis or after a new code merged to the dev branch.
* One other solution is to **only** accept vendor/ updates from core developers to prevent suspicious vendor files merging to base branch. Also add new lines to the build script to update vendor/ before each release otherwise we can forget.

I prefer the first method because it's the most clean, consistent and automated way of dealing with updating vendors.

**Comment by krhubert** [comment]
Leaving it here as motivation:

```$  time ./scripts/build-test-core.sh
./scripts/build-test-core.sh  0,43s user 0,15s system 0% cpu 9:36,96 total
$ dep init # + remove go get from dockerfile
$ time ./scripts/build-test-core.sh
./scripts/build-test-core.sh  1,44s user 0,46s system 9% cpu 19,682 total```

**Comment by ilgooz** [comment]
lets not forget removing `go get ./...` from Dockerfile after we integrated vendoring
