### ISSUE TITLE
return detailed validation errors from importer.From()

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#395]

**Comment by NicolasMahe** [comment]
Can you explain?

**Comment by ilgooz** [comment]
this empty [error](https://github.com/mesg-foundation/core/blob/222dd82/service/importer/import.go#L20) types hides all the useful validation errors generated by _Validate(source string)_

**Comment by NicolasMahe** [comment]
yes i agree.
Again, i suggest to NOT use `isValid` but directly the `Validation` function.

**Comment by krhubert** [comment]
todo close - we already return detalied list of validation errors
