### ISSUE TITLE
Hack with volumes for the CI

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#424]
When this PR is merged https://github.com/mesg-foundation/core/pull/419 we need to test if the following hack is still necessary. 
https://github.com/mesg-foundation/core/blob/060812cfe016838c4a29306d720eb1103d7d5e88/container/service_options.go#L77
https://github.com/mesg-foundation/core/blob/060812cfe016838c4a29306d720eb1103d7d5e88/service/start.go#L114

**Comment by krhubert** [comment]
It was tested by newst container refactr and it's working
