### ISSUE TITLE
Volume are not compatible with CircleCI

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#621]
The following test doesn't work in CircleCI because it couldn't create volume:

https://github.com/mesg-foundation/core/blob/ec382b501068f3e83f7b604e589bb6bc761b2d4e/service/volume_integration_test.go

One possibility to solve it, is to run the test in machine instead of docker:
https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-mount-volumes-to-docker-containers-

**Comment by krhubert** [comment]
close as delete volume is oneliner and we don't need to figure it out how to test it.
