### ISSUE TITLE
Cannot start any services

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#718]
I run a service that is present in my services list but this service cannot start because of an error when trying to connect to the core.

I just updated with the v0.7, I had this service running and so the core stopped during the update and start again and now all my previously running services cannot run anymore, even the one that were not running before.

I don't know if this is related to the v0.7 or just because the restart of the core was maybe brutal.

<img width="809" alt="screen shot 2019-01-16 at 10 38 48 pm" src="https://user-images.githubusercontent.com/1783126/51259846-8ddd4200-19df-11e9-9d63-5ca56ed19325.png">

**Comment by antho1404** [comment]
Error when trying to stop them.
```rpc error: code = Unknown desc = task: non-zero exit (1), task: non-zero exit (1), task: non-zero exit (1), task: non-zero exit (1)```

After deleting the services and reimport them it works fine but all my previous services are still not usable even after a restart of the core

**Comment by NicolasMahe** [comment]
Maybe related to
https://github.com/mesg-foundation/core/blob/047d33101171a1e67b72a45137851c13976eec71/database/service_db.go#L83-L89

I guess the service struct change and cannot be decoded anymore....

did you have the warning is the core log?

**Comment by antho1404** [comment]
I didn't see any warning and the command `list` or `details` were working correctly, just the call from the lib inside the service was triggering this error

Part of my logs, errors but no warning 
```
time="2019-01-16T15:51:10Z" level=info msg="deploying (0) system services..."
time="2019-01-16T15:51:10Z" level=info msg="starting system services..."
time="2019-01-16T15:51:10Z" level=info msg="all system services have been started"
time="2019-01-16T15:51:10Z" level=info msg="starting MESG Core version v0.7.0"
time="2019-01-16T15:51:10Z" level=info msg="server listens on [::]:50052"
time="2019-01-16T15:51:11Z" level=error msg="finished streaming call with code Unknown" error="database: service 8cbc5e9cb0f231142511c76b5065c6406c6e5d7c not found" grpc.code=Unknown grpc.method=ListenTask grpc.service=api.Service grpc
.start_time="2019-01-16T15:51:11Z" grpc.time_ms=9.756 span.kind=server system=grpc
time="2019-01-16T15:51:22Z" level=error msg="finished streaming call with code Unknown" error="database: service 8cbc5e9cb0f231142511c76b5065c6406c6e5d7c not found" grpc.code=Unknown grpc.method=ListenTask grpc.service=api.Service grpc
.start_time="2019-01-16T15:51:22Z" grpc.time_ms=0.154 span.kind=server system=grpc
time="2019-01-16T15:51:34Z" level=error msg="finished streaming call with code Unknown" error="database: service 8cbc5e9cb0f231142511c76b5065c6406c6e5d7c not found" grpc.code=Unknown grpc.method=ListenTask grpc.service=api.Service grpc
.start_time="2019-01-16T15:51:34Z" grpc.time_ms=0.108 span.kind=server system=grpc
```

**Comment by krhubert** [comment]
Move the database (just to save to reproduce error) and check if the error exists with fresh db

**Comment by antho1404** [comment]
I have a way to reproduce it. It is not the initial problem but certainly related.

In a first terminal run:
```
mesg-core service dev https://github.com/mesg-foundation/service-ethereum-erc20#feature/use-env-variables --env NODE_ENDPOINT=https://ropsten.infura.io/
```

Wait for it, everything is fine, we receive some events.

On a second terminal run:
```
mesg-core service dev https://github.com/mesg-foundation/service-ethereum-erc20#feature/use-env-variables
```

This one works fine and some events are emitted but the the first one now have the error `database: service 4d0a9c19f2e1ce3d3cf41c078b48c2ddd79f8f96 not found`

This is probably a problem with the sid, the 2 services have the same sid but 2 different hashes

**Comment by antho1404** [comment]
This is in fact 2 different problems:
- This issue is because we replace the hash in the db
- For the part that between the version there is some problems, it's because of the hashing method, we could have a basic hash function (json stringify + hash to remove the empty structs)

**Comment by antho1404** [comment]
Looks like using `omitempty` works to ignore it in the hash if it's empty

Bar string `hash:"name:Bar omitempty"`

this might be the solution

**Comment by NicolasMahe** [comment]
Nice!

**Comment by antho1404** [comment]
Another issue related here:
- deploy a service (v1)
- start the service (v1)
- update the service (v2)
- deploy the service (v2)
- stop the service (based on the sid) (v2)

We have no way to stop the initial service (v1). We have to do it using docker service rm

**Comment by krhubert** [comment]
I think this is outdated. closing

**Comment by antho1404** [comment]
yes this is solved with the introduction of instances :)
