### ISSUE TITLE
Improve test for deploy

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#723]
PR https://github.com/mesg-foundation/core/pull/690 reduce a lot the codecoverage. Let's improve it.

**Comment by krhubert** [comment]
@mesg-foundation/core todo: close or move to [cli issues](https://github.com/mesg-foundation/cli/issues)

**Comment by NicolasMahe** [comment]
I'm just closing this issue because of the new CLI and new deployment system
