### ISSUE TITLE
api: submit result: it's locking whole executions database

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/engine#793]
Currently, we do lock whole executions database by using transactions in LevelDB on find & write operations while submitting task results. And this is causing to significant delays while submitting multiple task results at the same time. Starting from x2 and it get worse around x5 submit results in a row. /cc @NicolasMahe 

* Either we need to switch to a more capable database that doesn't lock the whole database while doing writes to executions with different ids.

* Or we can use Go locks to prevent doing write operations for the executions with the same id to solve this problem temporarily.

Problematic [lines](https://github.com/mesg-foundation/core/blob/780bb47/api/submit_result.go#L42-L70).

### To reproduce
* Use current version of Core to see the slowness and after that modify _api>submit_result.go_ by replacing the funcs with the following to remove the transactions. Try again, It'll get way faster.

```go
// processExecution processes execution and marks it as complated or failed.
func (s *resultSubmitter) processExecution(executionID string, outputKey string, outputData []byte) (exec *execution.Execution, stateChanged bool, err error) {
	stateChanged = false

	exec, err = s.api.execDB.Find(executionID)
	if err != nil {
		return nil, false, err
	}

	exec.Service, err = service.FromService(exec.Service, service.ContainerOption(s.api.container))
	if err != nil {
		return s.saveExecution(s.api.execDB, exec, err)
	}

	var outputDataMap map[string]interface{}
	if err := json.Unmarshal(outputData, &outputDataMap); err != nil {
		return s.saveExecution(s.api.execDB, exec, fmt.Errorf("invalid output data error: %s", err))
	}

	if err := exec.Complete(outputKey, outputDataMap); err != nil {
		return s.saveExecution(s.api.execDB, exec, err)
	}

	return s.saveExecution(s.api.execDB, exec, nil)
}

func (s *resultSubmitter) saveExecution(db database.ExecutionDB, exec *execution.Execution, err error) (execOut *execution.Execution, stateChanged bool, errOut error) {
	if err != nil {
		if errFailed := exec.Failed(err); errFailed != nil {
			return exec, false, errFailed
		}
	}

	return exec, true, err
}
```

* Deploy location service:
```
./dev-cli service dev https://github.com/ilgooz/service-location
```

* Execute following command in 3 different terminal tabs at the same time:
```
while true; do ./dev-cli service execute -t locate -d ip=127.0.0.1 location; done
```

* Watch 3 terminal tabs to see how fast each execution completes.

**Comment by NicolasMahe** [comment]
Can you try to remove the lock on the database and see if it really solve the performance issue?

**Comment by ilgooz** [comment]
@NicolasMahe Yes it fastens everything to an eye blinking for 100 submit results. The problematic results was varying around 5-10 seconds per a few submit results to complete and much more for 100 of them like around 50secs.

**Comment by NicolasMahe** [comment]
@ilgooz @krhubert What do you think is taking most of the time? the `service.FromService` or `json.Unmarshal`?

**Comment by ilgooz** [comment]
> @ilgooz @krhubert What do you think is taking most of the time? the `service.FromService` or `json.Unmarshal`?
> `service.FromService` is actually calculating the hash with the data from the struct.. (this will be removed with PR #731).

They both take some time for sure but we can prevent it slowing done the whole system by not blocking the database. So, I think, we need to focus on changing to a more capable database to be able to do transactions per execution ids or use Go locks as a sort of workaround.

**Comment by antho1404** [comment]
I don't see any differences with or without the fix
- [Version normal](https://jumpshare.com/v/vB14FSXhx69fqF8UHMz9)
- [With the fix](https://jumpshare.com/v/OUMsFNax3amv1Ywyzf2y)

**Comment by ilgooz** [comment]
> I don't see any differences with or without the fix
> 
> * [Version normal](https://jumpshare.com/v/vB14FSXhx69fqF8UHMz9)
> * [With the fix](https://jumpshare.com/v/OUMsFNax3amv1Ywyzf2y)

Odd. Both of them seems to be slow. Are you sure that you use `./dev-core` and restarted the Core after changing the code?

@NicolasMahe can you also try to reproduce and give some feedbacks please?

**Comment by antho1404** [comment]
Just tried again,
- checkout to dev
- apply you fix on api/submit_result.go
- start `./dev-core`
- run the dev command on service-location
- open 3 terminals with the infinite execution loop
> no visible speed improvement.

**Comment by NicolasMahe** [comment]
closing this issue because not relevant with future development
