### ISSUE TITLE
Service start and stop doesn’t work sometimes

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#794]
Service start and stop doesn’t work well when a service doesn’t start correctly, for example when the service's code throw an error on start.

This issue needs to be re-tested first as I notice it a long time ago.

**Comment by NicolasMahe** [comment]
Updated version of this issue:
- Sometimes ('m not sure about the reason), when the engine is shut down, some services are still running in docker.
- Some other times, the service are nicely shutdown but the instance in the database is not deleted. thus on the next start, the engine think the services are running but they are not...

**Comment by antho1404** [comment]
we now use containers directly from the cli https://github.com/mesg-foundation/js-sdk/pull/199
