### ISSUE TITLE
Application listenEvent doesn't receive any event after many restart

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#802]
While developing an application that primary listen for event, the listener didn't receive any event after restarting the application for maybe the 20th or more time.

I'm thinking there is maybe a "limit" or a memory leak on the pubsub package.
The listenEvent stream seems to connect correctly (no error returned) but no new event where received.

Restarting the Core solve the problem..

**Comment by antho1404** [comment]
Could you try again, this issue is a bit old and we did a lot of modification on the event pubsub so this might be solved already

**Comment by antho1404** [comment]
Please reopen if you see the issue again.
