### ISSUE TITLE
Make sure generated SID is valid

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#806]
Related to PR #731 and #781 

The following line of code generate a not valid sid:
https://github.com/mesg-foundation/core/pull/731/files#diff-eeade751807b5e894d1f9a5b21390878R199
```
s.Sid = "_" + s.Hash
```

We need to make sure that the generated Sid is valid.
Otherwise, we could require service definition to have a Sid.

Sid validation of #781:
```
validate:"omitempty,printascii,max=63,domain"`
```

**Comment by krhubert** [comment]
We need to make sure that the generated Sid is valid.

There will be no generated sid in the #799 pr, because we don't need one

**Comment by NicolasMahe** [comment]
> There will be no generated sid in the #799 pr, because we don't need one
What do you mean there is not need for one?
