### ISSUE TITLE
Create a complete service for test

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#879]
We need a service that everyone can use and that test every features of the service.
eg: env, volumes, volumefrom, logs...

Like that when working on an update we can easily manual test with this all in one service and see detect potential regressions.

**Comment by ilgooz** [comment]
I like to have a few services in-fact. Still, running this service manually is not good. We need to automate it. Please see https://forum.mesg.com/t/automatize-manual-testing-for-core-true-integration-testing

**Comment by antho1404** [comment]
For information, I'm using this one for my manual testing

```json
{"sid":"testservice","name":"test service","tasks":[{"key":"taskx","inputs":[{"key":"foo","type":"String","object":[]},{"key":"bar","type":"String","object":[]}],"outputs":[{"key":"result","type":"String","object":[]}]}],"events":[{"key":"event","data":[{"key":"x","type":"Any","object":[]}]}],"dependencies":[{"key":"nginx","image":"nginx","volumes":["/etc/nginx"]}],"configuration":{"volumes":["/volume/test/"],"volumesFrom":["nginx"],"env":["ENVA=do_not_override","ENVB=override"]},"source":"QmYeaACibx89QkywySovtj4qg259Z8qfE1SLvWu2vPZ4uq"}
```

**Comment by NicolasMahe** [comment]
Is it on a repo?

**Comment by antho1404** [comment]
yes on ipfs QmYeaACibx89QkywySovtj4qg259Z8qfE1SLvWu2vPZ4uq

**Comment by NicolasMahe** [comment]
Closing because this has been done in https://github.com/mesg-foundation/engine/pull/1500
