### ISSUE TITLE
Service should explicitly acknowledge it's ready

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#912]
Related to https://github.com/mesg-foundation/core/issues/911

Currently, a service is consider running as soon as the container is created, but it doesn't mean the service is actually ready to receive task (the service is not listening for task).

I propose that services should explicitly acknowledge it's ready by either sending `ready` event (a system event) or call a new endpoint.

**Comment by antho1404** [comment]
Services could `"register"` in the core and get their identification (their token this way).
Another solution to consider is to use the health check from docker that will tell us when the service is ready and when the service stopped (even if the container is up)

**Comment by ilgooz** [comment]
Implementing https://github.com/mesg-foundation/engine/issues/1159#issuecomment-509395452 can solve this issue as well.

**Comment by NicolasMahe** [comment]
This is now done: services have to call the register endpoint to get a token mandatory to emit event and listen task.
