### ISSUE TITLE
Possible wallet access lost

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#940]
Now ethwallet service keeps wallets on volume.

Imagine a situation when someone run:

```
mesg-core service delete --all
```

And he removes system services as well. In that case, someone not only lost his wallet but also access to his service on the marketplace.

So core should either do not remove system services when deleting all and there should be a notification when deleting service that it might cause unrecoverable damage.

**Comment by antho1404** [comment]
this can be close, the api and cli now by default keep the data and you have to explicitly pass the `delete-data` argument/flag
