### ISSUE TITLE
Move service's log to manager

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#959]
In PR https://github.com/mesg-foundation/core/pull/904, the package manager has been introduced to manage the logic between service and container.

Following the logic of moving everything not related to the service's data outside the service package (https://github.com/mesg-foundation/core/issues/958), the service's log struct should also moved to the package manager.

Service log struct:
https://github.com/mesg-foundation/core/blob/dev/service/service.go#L88-L92

The service package should have only logic about the service's data and nothing more.

Basically, the file [`manager.go`](https://github.com/mesg-foundation/core/pull/904/files#diff-0cae5fb20442a4fd1b527406e43c6d8a) should only return struct define in its own package.

Please tell if you are agree to move namespace to manager or leave it like this.

**Comment by ilgooz** [comment]
same as https://github.com/mesg-foundation/core/issues/958#issuecomment-493016903
